0.8.10: limit entity selector filtering to selectors targeting > 1 non-player entities
Exception: if an entity is selected by UUID, it won't be filtered.
Exception: selectors that selecting players are no longer affected by filtering.